# Generated by Django 3.0.6 on 2021-07-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
    ]
