# Generated by Django 3.0.6 on 2021-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractor', '0002_auto_20210717_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='attrimg/', verbose_name='Иконка'),
        ),
    ]
