# Generated by Django 3.0.6 on 2021-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractor', '0003_auto_20210717_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attrimg/', verbose_name='Иконка'),
        ),
    ]
